#!/usr/bin/env python3
"""Prepare query-only NVIDIA confirmatory set; performs no API calls."""
import hashlib,json
from pathlib import Path
import pandas as pd
from sklearn.model_selection import train_test_split
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/"data/nvidia_confirm_v1";CURRENT=ROOT/"data/nvidia_current_v1/queries.jsonl"
POOL={"llama-3.1-8b-instruct":"meta/llama-3.1-8b-instruct","llama-3.3-70b-instruct":"meta/llama-3.3-70b-instruct","mistral-small-4-119b-2603":"mistralai/mistral-small-4-119b-2603","llama-3.2-3b-instruct":"meta/llama-3.2-3b-instruct","llama-3.3-nemotron-super-49b-v1":"nvidia/llama-3.3-nemotron-super-49b-v1","qwen3-next-80b-a3b-instruct":"qwen/qwen3-next-80b-a3b-instruct"}
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 OUT.mkdir(parents=True,exist_ok=True);frames=[]
 for split in ["train","validation","test"]:
  p=ROOT/f"data/example_data/routing_data/grouped/default_routing_{split}_data.jsonl";f=pd.read_json(p,lines=True).drop_duplicates("query");f["historical_split"]=split;frames.append(f)
 allq=pd.concat(frames).drop_duplicates("query");cur=pd.read_json(CURRENT,lines=True);tasks={"math","gsm8k","gpqa","mmlu","commonsense_qa","openbook_qa","arc_challenge","natural_qa","trivia_qa"};eligible=allq[allq.task_name.isin(tasks)&~allq["query"].isin(cur["query"])].copy();selected,_=train_test_split(eligible,test_size=len(eligible)-1000,random_state=20260725,stratify=eligible.task_name);selected=selected.sort_values(["task_name","query"]);keep=["task_name","query","ground_truth","metric","choices","task_id","embedding_id","historical_split"];selected[keep].to_json(OUT/"queries_sealed.jsonl",orient="records",lines=True,force_ascii=False)
 jobs=[{"query":r.query,"task_name":r.task_name,"model_name":m,"api_name":a,"repeat_index":rep,"requested_repeats":2} for r in selected.itertuples() for m,a in POOL.items() for rep in [1,2]];pd.DataFrame(jobs).to_json(OUT/"manifest.jsonl",orient="records",lines=True,force_ascii=False)
 prereg={"experiment_id":"nvidia_multitask_confirm_v1","created_utc":"2026-07-18","status":"preregistered_before_any_confirmatory_API_call","development_matrix":{"path":"data/nvidia_current_v1","queries":300,"role":"training_validation_only","planned_calls":3600},"confirmation":{"queries":1000,"seed":20260725,"models":POOL,"repeats":2,"planned_calls":12000,"overlap_with_development":0},"baselines":["always-strong:mistral-small-4-119b-2603","always-cheap:llama-3.2-3b-instruct","random-routing:1000 simulations","round-robin","router","oracle:non-deployable"],"primary_metrics":["accuracy","actual_token_cost","size_proxy","coverage","harm","rescue"],"statistics":{"paired_bootstrap_replicates":10000,"seed":20260726,"confidence":0.95},"success_criteria":{"test_queries_at_least":1000,"small_model_coverage_at_least":0.20,"actual_cost_saving_at_least":0.15,"accuracy_delta_ci95_lower_at_least":-0.005,"harm_rate_at_most":0.03,"nondegenerate_tasks_at_least":2},"nondegenerate_task_definition":"at least 20 queries and at least two models each selected on >=10% of that task","decision_rule":"all criteria must pass; otherwise report systematic negative result for query-only routing","reporting":["overall and per-task Accuracy-Cost Pareto","point estimates and paired CI","harm/rescue","all baselines","all failed criteria"],"router_freeze_rule":"train/select only on current-300 development matrix; hash router before reading confirmatory outcomes"}
 (OUT/"PREREGISTRATION.json").write_text(json.dumps(prereg,indent=2));(OUT/"PREREGISTRATION.sha256").write_text(sha(OUT/"PREREGISTRATION.json")+"  PREREGISTRATION.json\n");seal={"queries_sha256":sha(OUT/"queries_sealed.jsonl"),"manifest_sha256":sha(OUT/"manifest.jsonl"),"metrics_read":False,"api_calls_started":False};(OUT/"SEAL.json").write_text(json.dumps(seal,indent=2));print(json.dumps({"eligible":len(eligible),"selected":len(selected),"tasks":selected.task_name.value_counts().to_dict(),"jobs":len(jobs),"overlap":len(set(selected["query"])&set(cur["query"])),"seal":seal},indent=2))
if __name__=="__main__":main()
