#!/usr/bin/env python3
"""Create the pre-execution budget seal and preregistration amendment."""
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data/finance_router/finrome_legacy_v2_confirmatory';PILOT=ROOT/'run_logs/finrome_legacy_v2_cost_pilot/PILOT_REPORT.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def main():
 pilot=json.loads(PILOT.read_text());assert pilot['status']=='PILOT_COMPLETE';pre=json.loads((DATA/'PREREGISTRATION.json').read_text());assert pre['status']=='PREREGISTERED_BEFORE_ANY_NEW_OUTCOMES'
 amendment={'id':'AMENDMENT_001','created_at':datetime.now(timezone.utc).isoformat(),'timing':'before any formal outcome calls','reason':'FinReflectKG availability forced ObliQA allocation from 450 to 525; expected compliance dual-judge count was not updated in original preregistration','original_expected_judge_calls':10800,'corrected_expected_judge_calls':12600,'original_total_calls':20400,'corrected_total_calls':22200,'primary_hypothesis_unchanged':True,'sample_size_unchanged':800,'risk_strata_unchanged':{'high':600,'medium':200},'policy_unchanged':True,'pilot_prohibited_for_efficacy':True}
 dump(DATA/'AMENDMENT_001.json',amendment)
 projected=pilot['projected_formal'];execution={'status':'SEALED_AWAITING_EXPLICIT_BUDGET_AUTHORIZATION','created_at':datetime.now(timezone.utc).isoformat(),'pilot_contract':pilot['contract'],'pilot_observed_cost_usd':pilot['observed_cost_usd'],'projected_cost_usd':projected,'budget_caps_usd':{'overall':42.0,'zhipu':36.0,'deepseek':3.0,'qwen_combined':1.5},'budget_buffer_over_projection':42/projected['total_cost_usd']-1,'planned_calls':{'answers':9600,'judges':12600,'total':22200},'token_limits':{'answers':{'glm-5.2':4096,'other_models':512,'glm_empty_escalation':[8192,16384]},'judges':{'glm-5.2':2048,'deepseek-chat':512,'qwen-plus':512}},'concurrency':{'global':6,'per_provider':2},'retry_rule':'maximum 2 retries for timeout, 429 and 5xx; no retry loop for authentication, arrearage, permission or other 4xx','hard_stops':['provider authentication or arrearage error','overall or provider budget cap reached','non-transient failure rate >1% after at least 100 calls for a provider','successful-but-empty final answer rate >2% after at least 50 GLM answer calls','no increase in valid unique keys across a full retry pass','task/policy/hash mismatch'],'estimated_wall_time':'approximately 72-96 hours at pilot latency and configured concurrency','stopping_rule':'complete all planned unique keys; no efficacy-based early stopping','human_review':'PENDING only','formal_outcome_read_before_seal':False,'hashes':{'preregistration':sha(DATA/'PREREGISTRATION.json'),'amendment':sha(DATA/'AMENDMENT_001.json'),'frozen_policy':sha(DATA/'FROZEN_POLICY.json'),'tasks':sha(DATA/'tasks.jsonl'),'pilot_report':sha(PILOT)}}
 dump(DATA/'EXECUTION_SEAL.json',execution);(DATA/'EXECUTION_SEAL.sha256').write_text(sha(DATA/'EXECUTION_SEAL.json')+'  EXECUTION_SEAL.json\n');print(json.dumps(execution,ensure_ascii=False,indent=2))
if __name__=='__main__':main()
